name: udacity-deployml-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - fastapi
  - uvicorn
  - scikit-learn
  - flake8
  - pytest
  - pip  # Important to ensure pip is available