name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda with Python 3.11
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: udacity-deployml-env
        environment-file: environment.yml
        python-version: 3.11
        auto-activate-base: false
        channels: conda-forge

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest